FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

ARG VITE_API_URL=http://localhost:8000
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build
RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "dist", "-s", "-l", "3000"]
